syncserver: "http://dev:8888"
zap:
  level: 'debug'
  format: 'console'
  prefix: '[RedissyncerT]'
  director: 'log'
  link-name: 'latest_log'
  show-line: true
  encode-level: 'LowercaseColorLevelEncoder'
#  stacktrace-key: 'stacktrace'
  log-in-console: true
